### ISSUE TITLE
api.i-meto.com ssl证书过期，导致服务不可用 （20220926 07:59:59 过期）

### ISSUE THREAD

**Issue by mycpen** [MoePlayer/hexo-tag-aplayer#116]
![image](https://user-images.githubusercontent.com/72154342/192225873-68565c72-280d-4384-a4c1-f43c5877a8e0.png)

![image](https://user-images.githubusercontent.com/72154342/192225973-2b3c5737-fa90-4109-bd48-f94918e0296b.png)

**Comment by QuestionMark001** [comment]
我也遇到了这样的问题，导致歌单部分一片空白。

**Comment by mycpen** [comment]
已恢复
