### ISSUE TITLE
hexo-blog-encrypt 与  hexo-tag-aplayer 的兼容问题

### ISSUE THREAD

**Issue by GZ-Metal-Cell** [MoePlayer/hexo-tag-aplayer#124]
如果使用 hexo-blog-encrypt 给文章加密，那么解密后 hexo-tag-aplayer 会失效，该如何解决？

**Comment by EthanLiu6** [comment]
解决了吗老哥

**Comment by GZ-Metal-Cell** [comment]
> 解决了吗老哥

解决了，需要在 `_config.yml` 关闭 aplayer 的预加载：

```yml
aplayer:
    asset_inject: false
```

改为在需要的地方手动加载 `APlayer.css` 和 `APlayer.min.js`。

**Comment by EthanLiu6** [comment]
> > 解决了吗老哥
> 
> 解决了，需要在 `_config.yml` 关闭 aplayer 的预加载：
> 
> ```yaml
> aplayer:
>     asset_inject: false
> ```
> 
> 改为在需要的地方手动加载 `APlayer.css` 和 `APlayer.min.js`。



谢谢你哈，其实我之前就关了，发现并没有遇到这样的错误，感谢您的回复哈，不过我还有个问题，就是加密文章解密查看后目录怎么才能看到

**Comment by GZ-Metal-Cell** [comment]
> > > 解决了吗老哥
> > 
> > 
> > 解决了，需要在 `_config.yml` 关闭 aplayer 的预加载：
> > ```yaml
> > aplayer:
> >     asset_inject: false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 改为在需要的地方手动加载 `APlayer.css` 和 `APlayer.min.js`。
> 
> 谢谢你哈，其实我之前就关了，发现并没有遇到这样的错误，感谢您的回复哈，不过我还有个问题，就是加密文章解密查看后目录怎么才能看到

这个问题有点复杂，根据 [hexo-blog-encrypt](https://github.com/D0n9X1n/hexo-blog-encrypt?tab=readme-ov-file#after-decrypt-event) 里所说，在文章解密完成时会派发事件 `'hexo-blog-decrypt'`，需要找到你生成目录的代码，在监听到事件 `'hexo-blog-decrypt'` 后再执行一遍生成目录的代码，不同 hexo 主题可能不太一样……

**Comment by EthanLiu6** [comment]
> > > > 解决了吗老哥
> > > 
> > > 
> > > 解决了，需要在 `_config.yml` 关闭 aplayer 的预加载：
> > > ```yaml
> > > aplayer:
> > >     asset_inject: false
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 改为在需要的地方手动加载 `APlayer.css` 和 `APlayer.min.js`。
> > 
> > 
> > 谢谢你哈，其实我之前就关了，发现并没有遇到这样的错误，感谢您的回复哈，不过我还有个问题，就是加密文章解密查看后目录怎么才能看到
> 
> 这个问题有点复杂，根据 [hexo-blog-encrypt](https://github.com/D0n9X1n/hexo-blog-encrypt?tab=readme-ov-file#after-decrypt-event) 里所说，在文章解密完成时会派发事件 `'hexo-blog-decrypt'`，需要找到你生成目录的代码，在监听到事件 `'hexo-blog-decrypt'` 后再执行一遍生成目录的代码，不同 hexo 主题可能不太一样……

好的，谢谢您的解答
