### ISSUE TITLE
API ` fs.SyncWriteStream` abandoned in node8

### ISSUE THREAD

**Issue by edward-p** [MoePlayer/hexo-tag-aplayer#16]
``` bash
$ hexo g
(node:3876) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
...
```

**Comment by grzhan** [comment]
See https://github.com/hexojs/hexo/issues/2598
Therefore I updated `hexo-fs` in `hexo-tag-aplayer@2.0.3`.
Please update your plugin, then this issue would be resolved. 
If you do still encounter issues, please let us know.

**Comment by edward-p** [comment]
@grzhan Now can be closed.Thanks for your work.😬
