### ISSUE TITLE
unknown block tag: aplayer

### ISSUE THREAD

**Issue by xzq8** [MoePlayer/hexo-tag-aplayer#17]
![Uploading image.png…]()

**Comment by dixyes** [comment]
at first make sure you have hexo-tag-aplayer installed in your hexo dir

    npm install -s hexo-tag-aplayer

if possiable , provide a available screenshot

**Comment by xzq8** [comment]
I have installed it, but NPM reported it wrong.

**Comment by dixyes** [comment]
can you provide any log, stacktrace,
And your environment

**Comment by xzq8** [comment]
I sent you a screenshot with mail

**Comment by wjm2038** [comment]
You may want to try upload that screenshot in **this issue** again

**Comment by xzq8** [comment]
I know what's wrong ， need to update the hexo to the latest    
   https://github.com/hexojs/hexo/issues/2573
