### ISSUE TITLE
文字格式支持

### ISSUE THREAD

**Issue by xtz1990** [MoePlayer/hexo-tag-aplayer#18]
法语歌有法语特殊符号的话播放会出错，希望能完善，谢谢。

**Comment by grzhan** [comment]
Could you please provide a short but complete example which demonstrates the problem ?

**Comment by xtz1990** [comment]
![](https://i.loli.net/2017/09/19/59c06f4217fff.png)
![](https://i.loli.net/2017/09/19/59c06f4e7a305.png)

**Comment by grzhan** [comment]
抱歉这么久才回复。
尝试下载了同名歌曲，以同样的文件名部署在本地环境上，似乎没有问题可以正常播放，如图：

![case screenshot](https://ws4.sinaimg.cn/large/006tNbRwgy1fkg2llcwqej30la03cmx8.jpg)

请检查是否更新插件到最新版本，并确认引用的音乐文件路径无误

另，默认不开启自动播放，因此我本地测试时的插件调用写法是：

> {% aplayer "Même si c'est très loin" "Fréro Delavega" "Même si c'est très loin - Fréro Delavega.mp3"%}
