### ISSUE TITLE
Release v2.0.6 on npm

### ISSUE THREAD

**Issue by DIYgod** [MoePlayer/hexo-tag-aplayer#20]
I need pjax support on my blog. 😂

**Comment by grzhan** [comment]
I updated `v2.0.6`, please tell me if there are any problems. 
Sorry for my neglect.

**Comment by DIYgod** [comment]
版本号更新了，但是 index.js 并没有更新...是不是 npm publish 之前没执行 gulp

**Comment by grzhan** [comment]
I forgot to compile the file `index.es` with Babel.
It should be fixed at `v2.0.7`

**Comment by DIYgod** [comment]
It works well on my blog, thanks!

Try [best-players-in-hexo](https://diygod.me/best-players-in-hexo/)

**Comment by grzhan** [comment]
@DIYgod  Thanks for your continued support!
