### ISSUE TITLE
Support Meting API

### ISSUE THREAD

**Issue by DIYgod** [MoePlayer/hexo-tag-aplayer#21]
Reference: https://github.com/metowolf/MetingJS

cc @metowolf

**Comment by DIYgod** [comment]
Make self-hosted Meting API: https://github.com/metowolf/MetingJS/issues/1#issuecomment-349229512

**Comment by Edenharder** [comment]
It will be great if you can give an exact example how to use the Meting API.

**Comment by grzhan** [comment]
Support MetingJS in version `3.0.0-beta.5`
Please report us if you find any problem.
