### ISSUE TITLE
Support custom script directory

### ISSUE THREAD

**Issue by syhily** [MoePlayer/hexo-tag-aplayer#24]
For some cdn purpose.

**Comment by dixyes** [comment]
see README.md:

    Customization

    You can modify variables scriptDir(default: "/assets/js/" ) in index.js according to your blog's directory structure.

**Comment by syhily** [comment]
No modification on source code would be hard for users, just move it to site configuration could be better.

I have implemented this feature, a new pull request would be submitted soon.
