### ISSUE TITLE
[建议] 设置默认播放模式

### ISSUE THREAD

**Issue by WrRan** [MoePlayer/hexo-tag-aplayer#26]
您好，我在使用hexo-tag-aplayer时，发现播放模式默认为循环播放，请问可以如何调整设置，使其“列表播放”呢？

**Comment by grzhan** [comment]
你好，对于播放列表的播放方式，应该可以在 `{%aplayerlist%}` 中的 `mode` 选项中进行设置。

-------------------------------------------------------------------

You can set `mode` option to select which play mode you want.
