### ISSUE TITLE
请问怎么使用？能播放在线歌曲么？

### ISSUE THREAD

**Issue by 54chenkai** [MoePlayer/hexo-tag-aplayer#29]
文档有点简略，没有看太懂。歌曲的信息和歌曲文件都是需要自己上传的么？可不可以播放在线的歌曲？能从其它网站账户导入歌单么

**Comment by grzhan** [comment]
你好，目前插件的主要使用形式以自己上传音乐文件然后引用为主

关于歌曲信息（歌曲名、作者名等）可以遵从本插件的 TAG 形式进行填写。

例如有一个歌曲文件，歌曲名为 `foo`， 作者名为 `bar`，歌曲文件的 URL 为 `/music/xxx.mp3` 

那么在博客文章中可以插入：

```
{% aplayer "foo" "bar" "/music/xxx.mp3" %}
```

这样在文章中就会出现包含 aplayer 的播放器

如果直接引用其他网站外部的音乐文件，可能会遇到[跨域问题](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS)，因此可以考虑本插件以外的其他方案来实现外部音乐的引用。

例如网易云音乐就支持[外链插件](http://music.163.com/#/outchain/1/1678955/)，可以考虑使用。
