### ISSUE TITLE
如何使用playlist

### ISSUE THREAD

**Issue by Livingston34** [MoePlayer/hexo-tag-aplayer#31]
您好,我使用了playlist 说Unexpected end of JSON input . 求解释?

**Comment by grzhan** [comment]
可能是使用 playlist 时格式出现问题，请问是如何使用 playlist 的？
方便的话请提供调用 `hexo-tag-aplayer` 部分的文章原文（源码）

**Comment by Livingston34** [comment]
{% aplayerlist %}
{
	"narrow": false,						// Optional, narrow style
    "autoplay": true,						// Optional, autoplay song(s), not supported by mobile browsers
    "mode": "random",						// Optional, play mode, can be `random` `single` `circulation`(loop) `order`(no loop), default: `circulation`
    "showlrc": 3,							// Optional, show lrc, can be 1, 2, 3
    "mutex": true,							// Optional, pause other players when this player playing
    "theme": "#e6d0b2",						// Optional, theme color, default: #b7daff
	"preload": "metadata",					// Optional, the way to load music, can be 'none' 'metadata' 'auto', default: 'auto'
	"listmaxheight": "513px",				// Optional, max height of play list
    "music": [
        {
            "title": "CoCo",
            "author": "Jeff Williams",
            "url": "caffeine.mp3",
            "pic": "caffeine.jpeg",
            "lrc": "caffeine.txt"
        },
        {
            "title": "アイロニ",
            "author": "鹿乃",
            "url": "irony.mp3",
            "pic": "irony.jpg"
        }
    ]
}
{% endaplayerlist %}

我用的是readme文件里面

**Comment by grzhan** [comment]
你好，在 README 中， 出现的形如 `// Optional: ...` 这些注释只是示意用，正式使用时候是不能解析的。
可以参考以下方式来使用播放列表：

```
{% aplayerlist %}
{
    "music": [
        {
            "title": "Même si c'est très loin",
            "author": "Fréro Delavega",
            "url": "Même si c'est très loin - Fréro Delavega.mp3"
        },
        {
            "title": "Säkkijärven polkka",
            "author": "浜口史郎",
            "url": "sakkijarven.mp3"
        }
    ]
}
{% endaplayerlist %}
```

**Comment by Livingston34** [comment]
谢谢 指导
