### ISSUE TITLE
开启 meting 后，用 {% aplayer %} 标签报错无法显示

### ISSUE THREAD

**Issue by reuixiy** [MoePlayer/hexo-tag-aplayer#36]
比如[这个页面](https://reuixiy.github.io/beautiful/notnow/2018/01/11/a-song-of-ice-and-fire.html)（[原文](https://raw.githubusercontent.com/reuixiy/reuixiy.github.io/master/beautiful/notnow/2018/01/11/a-song-of-ice-and-fire.md)），我用`{% aplayer %}`标签，F12 后能看到报错，不知为什么……

而[这个页面](https://reuixiy.github.io/uncategorized/2010/01/01/test.html)（[原文](https://raw.githubusercontent.com/reuixiy/reuixiy.github.io/master/uncategorized/2010/01/01/test.md)），我也是用`{% aplayer %}`标签，却能正确显示，不知为什么……

然后，按下 F12，对比上面两种情况，发现第一个页面加载了 MetingJS，而第二个页面没有加载（可能我还用`{% aplayerlist %}`标签吧）……

所以，我觉得解决方案应该是：在用`{% aplayer %}`标签的页面去除添加的 meting 链接（因为用`{% aplayerlist %}`标签的页面没有 meting，就能显示）。然代码小白，不知如何处理……

另外，[这个页面](https://reuixiy.github.io/about/index.html)（[原文](https://raw.githubusercontent.com/reuixiy/reuixiy.github.io/master/about/index.md)）用`{% meting %}`标签，没问题……

**Comment by grzhan** [comment]
请提供一下存在问题的博客原文，以及插件的版本号

**Comment by grzhan** [comment]
在之前的版本的 MetingJS 中，其播放器和原生 APlayer 存在冲突
不过作者应该修复了，收到提供的有关信息后我会检查一下

**Comment by reuixiy** [comment]
版本是 3.0.3，博客原文链接见上面，我修改了描述，感谢 ~

**Comment by grzhan** [comment]
@reuixiy 我在自己的主题没有复现这个问题，应该是插件在植入 Meting 和 Aplayer 过程中出现了问题，请提供使用的主题名称

**Comment by grzhan** [comment]
@reuixiy 我在自己的主题没有复现这个问题，应该是插件在植入 Meting 和 Aplayer 过程中出现了问题，请提供使用的主题名称

**Comment by reuixiy** [comment]
NexT v5.1.3

**Comment by reuixiy** [comment]
现在发现问题已解决
thx

**Comment by linwhitehat** [comment]
你好，我的博客使用MeingJS插入音乐，但是加载不出来，请求响应是500，请问知道是什么情况吗？这是加载音乐的博客页面地址https://linwhitehat.github.io/guest/

**Comment by reuixiy** [comment]
原来我还提过这样一个 Issue……看了下，我这是 OK 的，估计是你的网络问题？

![2020-02-14-19-23-53](https://user-images.githubusercontent.com/28993043/74526994-99db6080-4f5f-11ea-9bc9-4c8c3ac70d84.png)

**Comment by linwhitehat** [comment]
> 原来我还提过这样一个 Issue……看了下，我这是 OK 的，估计是你的网络问题？
> 
> ![2020-02-14-19-23-53](https://user-images.githubusercontent.com/28993043/74526994-99db6080-4f5f-11ea-9bc9-4c8c3ac70d84.png)

是参数出现问题，抱歉，已经更正，可正常播放
