### ISSUE TITLE
关于meting参数说明的建议

### ISSUE THREAD

**Issue by tianma8023** [MoePlayer/hexo-tag-aplayer#37]
您在`readme`中是这样说明的：
```
<!-- Simple example (id, server, type)  -->
{% meting "60198" "netease" "playlist" %}

<!-- Advanced example -->
{% meting "60198" "netease" "playlist" "autoplay" "mutex:false" "listmaxheight:340px" "preload:none" "theme:#ad7a86"%}
```
在这个 Advanced example 中，并未包含 `mode` 参数，希望可以加上。

另外，阅读源码可以知道，前三个参数(id, server, type)是必须的且有序时才能生效，其他非必须的参数（除了 `autoplay` 外）都需要 `参数名:` 的格式才能生效，并且可以是无序的。

我的建议是，这些信息应该在您的`readme`中作出声明，方便普通使用者快速合理使用 XD

**Comment by grzhan** [comment]
感谢反馈与支持！我会依照意见修改的。

**Comment by tianma8023** [comment]
@grzhan 在使用过程中还是发现了如下一个问题：
在您的依赖中 `MetingJS` 的版本是 `1.1.1` , 而在 [MetingJS#Options](https://github.com/metowolf/MetingJS#option) 中可以看到 `data-mode` 参数已经 deprecated，而反应到这里的结果就是 `mode` 参数失效。

**Comment by grzhan** [comment]
你好，关于 APlayer 与 Meting 的版本兼容问题我计划在清明节前后进行跟进。
也欢迎在此之前提交修复此 issue 的 pr，我会在审核后合并。

**Comment by grzhan** [comment]
@tianma8023 抱歉过了这么久才修正
有空的时候请更新 `hexo-tag-aplayer@3.0.4` 查看是否已经修复问题
