### ISSUE TITLE
求一个文章页面以外使用aplay的方法

### ISSUE THREAD

**Issue by j0oey** [MoePlayer/hexo-tag-aplayer#39]
想在侧边栏加上aplay的播放器，但是不能像文章页面一样添加。

**Comment by grzhan** [comment]
请提供您使用的主题，一般来说 Hexo 通过插件来插入代码具有一定局限性
另外可以考虑直接在主题的侧边栏代码中直接添加 [Aplayer](https://github.com/MoePlayer/APlayer) 的调用代码

**Comment by ghost** [comment]
@grzhan 直接添加 Aplayer 的调用代码没有效果。只会显示添加的代码。
