### ISSUE TITLE
出现"An auido error has occurred,player will skip forward in 2 seconds."错误！

### ISSUE THREAD

**Issue by championheng** [MoePlayer/hexo-tag-aplayer#40]
[问题截图](http://i1.bvimg.com/633787/8c365124b3ab75fd.png)
[代码截图](http://i1.bvimg.com/633787/13ab430fc13dafc7.png)

如上，希望能够尽快得到您的回复，谢谢啦~

**Comment by championheng** [comment]
引用直接音乐文件的话，需要将音乐文件缓冲到本地，然后由GitHub进行托管，这样的话会不会占用较多内存资源。我先试试Meting，感谢回复~

**Comment by championheng** [comment]
问题已经解决，谢谢解答，使用Meting解决问题~

**Comment by CNXYQ** [comment]
楼主你好，请问可以具体教一下怎么做吗

**Comment by lxp731** [comment]
我也遇到这个问题了，因为用的是鹅厂音乐的歌单，后来改用网抑云的歌单就好了。
