### ISSUE TITLE
使用Meting，进行“mode:random”参数配置后无法生效？

### ISSUE THREAD

**Issue by championheng** [MoePlayer/hexo-tag-aplayer#41]
进行如下配置：
`{% meting "117523093" "netease" "playlist" "autoplay" "mode:random" "mutex:true" "listmaxheight:340px" "preload:auto" "theme:#000000" %}`

进入："http://localhost:4000/music/"页面后并不能进行随机播放？

如图：

[网页截图](http://i4.bvimg.com/633787/a72b354d27515dd0.png)

期待您的回复~Thanks

**Comment by grzhan** [comment]
应该是 #37 在提到的问题，插件没有兼容新版本的 MetingJS
刚刚修复了这个问题，请升级 `hexo-tag-aplayer` 至 `3.0.4` ， 并使用 `order:random` 来控制随机播放（详情参考更新的 README）

**Comment by dhengyi** [comment]
问题已解决，谢谢~期待移动端也能早点支持自动播放哦
