### ISSUE TITLE
引入MeingJS之后播放无限制刷新（非页面刷新）

### ISSUE THREAD

**Issue by wksama** [MoePlayer/hexo-tag-aplayer#47]
播放不成功，进度条走1s之后就又回到0
console.log报错内容如下：
  APlayer v1.10.1 af84efb  http://aplayer.js.org 

Meting.min.js:1 
  MetingJS v1.2.0  https://github.com/metowolf/MetingJS 

/2018/07/28/%E5%86%99%E5%9C%A8%E5%89%8D%E9%9D%A2%E7%9A%84%E8%AF%9D/#more:1 Mixed Content: The page at 'https://wencochen.github.io/2018/07/28/%E5%86%99%E5%9C%A8%E5%89%8D%E9%9D%A2%E7%9A%84%E8%AF%9D/#more' was loaded over HTTPS, but requested an insecure script 'http://v3.jiathis.com/code/jia.js'. This request has been blocked; the content must be served over HTTPS.

![12121](https://user-images.githubusercontent.com/38133076/43367285-2548be6a-937d-11e8-8610-84ba01a06ab6.png)

**Comment by WencoChen** [comment]
发现报错是由于框架的jiathis不支持https,把那个文件删除了就没报错了，但是还是无限刷新，不知道是不是由于音乐是我自己云盘上面的原因，因为之前没引入MeingJS的时候是没问题的，随便换了个ID没问题了
