### ISSUE TITLE
在meting标签是否只能在文章内生效，似乎加在模板页面不起效果

### ISSUE THREAD

**Issue by ZvonimirSun** [MoePlayer/hexo-tag-aplayer#53]
请问怎样才能在全站添加呢，我希望在全站都能看到左下角有固定模式的播放器。我用的是hexo-theme-next主题。十分感谢

**Comment by ghost** [comment]
在md里插入播放器后你们去看生成的html文件。直接复制那段代码到你想要的地方，改下歌单id就好了

**Comment by ZvonimirSun** [comment]
@track177 谢谢，我现在就是这样解决的。
