### ISSUE TITLE
aplayer显示异常

### ISSUE THREAD

**Issue by azhaYOLO** [MoePlayer/hexo-tag-aplayer#54]
在hexo主题yilia中，aplayer的界面显示异常
![screenshot of photos _ azha s blog](https://user-images.githubusercontent.com/19308130/45588523-9f86de00-b948-11e8-82d8-d466134c5f5f.jpg)

**Comment by Flower233pks** [comment]
我的也是，为什么没人回答qaq？

**Comment by menhood** [comment]
样式没加载？或者样式冲突？ 排查下呗，看起来应该不是Aplayer的锅

**Comment by Flower233pks** [comment]
我想问一下，是直接`npm install aplayer --save`之后，在文章中加上`{% aplayer "See You Again" "Wiz Khalifa" "http://olfa3o6q1.bkt.clouddn.com/See%20You%20Again.mp3" "http://olfa3o6q1.bkt.clouddn.com/See%20You%20Again.lrc" %}`这种就行吗……

**Comment by Flower233pks** [comment]
不需要什么额外的操作了？

**Comment by menhood** [comment]
试一下不就好了[Doge]

**Comment by Flower233pks** [comment]
？？？[黑人问号]

**Comment by Flower233pks** [comment]
所以有没有哪位开发者可以来帮忙解决一下这个问题啊……

**Comment by Flower233pks** [comment]
大概就是这种情况
![image](https://user-images.githubusercontent.com/42432004/52760266-e426ba80-3049-11e9-88f0-f4c4fda02b74.png)

**Comment by Flower233pks** [comment]
诶说真的，这个Issue好几个月没人解决让我感到很自闭（毙）啊

**Comment by menhood** [comment]
有没有地址，我去瞧瞧 ~~菜的抠脚应该够用~~

**Comment by Flower233pks** [comment]
http://www.orchidany.cf/2019/02/12/To-do-List/#more
谢啦

**Comment by Flower233pks** [comment]
问题已解决。是aplayer插件和hexo-tag-aplayer插件冲突所致

**Comment by Flower233pks** [comment]
然后需要删除`aplayer`保留`hexo-tag-aplayer` @Azha666

**Comment by azhaYOLO** [comment]
好的 谢谢解答：）@Flower233pks
