### ISSUE TITLE
can't change the play time by click or drag the side bar

### ISSUE THREAD

**Issue by cncws** [MoePlayer/hexo-tag-aplayer#73]
I create a new hexo blog for test:
```
hexo init test
cd test
npm install
hexo server
npm install --save hexo-tag-aplayer
```
Then there is a post "Hello world". I add this in that post.
```
{% aplayer "なのです!" "ななひら" "/musics/ななひら - なのです!.mp3" "/musics/ななひら - なのです!.jpg" "lrc:/musics/ななひら - なのです!.lrc" %}
```
There are the problems:
1. The play time will go back to 0 when you click the time bar.
2. Can't initialize the lrc. The console print the follow message: TypeError: Cannot read property '_id' of undefined.
Hope you can help me. Where are the problems?
(anonymous) @ (index):90

**Comment by chenpeanut** [comment]
I create a new hexo blog for test:
```
hexo init test
cd test
npm install
hexo server
npm install --save hexo-tag-aplayer
```
Then there is a post "Hello world". I add this in that post.
```
{% aplayer "なのです!" "ななひら" "/musics/ななひら - なのです!.mp3" "/musics/ななひら - なのです!.jpg" "lrc:/musics/ななひら - なのです!.lrc" %}
```
There are the problems:
1. The play time will go back to 0 when you click the time bar.
2. Can't initialize the lrc. The console print the follow message: TypeError: Cannot read property '_id' of undefined.
Hope you can help me. Where are the problems?
(anonymous) @ (index):90

**Comment by khoint0210** [comment]
How you fix the bug for this one `The play time will go back to 0 when you click the time bar`

**Comment by cncws** [comment]
I don't use hexo-tag-aplayer anymore. I use the script directly.
