### ISSUE TITLE
谷歌浏览器下无法调节进度

### ISSUE THREAD

**Issue by cncws** [MoePlayer/hexo-tag-aplayer#77]
aplayer的实例
在谷歌浏览器中，点击进度条调节时间时重新回到0； 但是别人的博客可以正常调节时间。
在IE和Edge中，点击进度条可以正常调节时间。
有谁知道是怎么一回事吗？

**Comment by aweiu** [comment]
我也遇到这个问题了，您是咋解决的？

**Comment by cncws** [comment]
问题已经关闭也被找出来了。。你也饱受其害吧。。。现实情况是我什么都没做。自己好的。
之前：aplayer，静态服务器下异常，发布后的服务器下正常。
现在：aplayer+metingjs，均正常。
