### ISSUE TITLE
如何适配theme-next-pjax？

### ISSUE THREAD

**Issue by makisevon** [MoePlayer/hexo-tag-aplayer#90]
使用theme-next-pjax后不能正常加载，需刷新。

**Comment by du5** [comment]
dplayer1 标签直接没了

**Comment by makisevon** [comment]
> dplayer1 标签直接没了

参考 [pjax导致无法初始化aplayer音乐播放器](https://yxyvpn.com/2020/04/15/pjax%E5%AF%BC%E8%87%B4%E6%97%A0%E6%B3%95%E5%88%9D%E5%A7%8B%E5%8C%96aplayer%E9%9F%B3%E4%B9%90%E6%92%AD%E6%94%BE%E5%99%A8/) 解决。
