### ISSUE TITLE
an audio error has occurred

### ISSUE THREAD

**Issue by AustinWilliam117** [MoePlayer/hexo-tag-aplayer#99]
我按照aplayer的配置后，出现了这样的问题。
![2021-01-04_23-15](https://user-images.githubusercontent.com/56376062/103549660-b28b9680-4ee2-11eb-831e-45cc34eb57c6.png)

我一开始以为是qq音乐的问题，或者是主题的问题。但我换了next和yilia主题后都不行。

{% aplayer "歌曲名" "歌手名" "https://www.kugou.com/song/#hash=55F4335A672A3FA0E84276116FC1AA89&album_id=960994" %}

配置
hexo 5.3.0

**Comment by AustinWilliam117** [comment]
{% aplayer "歌曲名" "歌手名" "https://www.kugou.com/song/#hash=55F4335A672A3FA0E84276116FC1AA89&album_id=960994"%}

**Comment by AustinWilliam117** [comment]
已解决。

**Comment by zeno980** [comment]
> 已解决。

请问如何解决的呢
